name: brain
version: 0.0.0
description:
publish_to: none
dependencies:
  angel_common: ^1.0.0
  angel_hot: ^1.0.0
  angel_orm: ^1.0.0-alpha
  angel_security: ^1.0.0
  github: ^3.0.0
  # gitter: ^0.1.1
  polymer: ^1.0.0-rc.19
  polymer_elements: ^1.0.0-rc.10
dev_dependencies:
  angel_orm_generator: ^1.0.0-alpha
  angel_test: ^1.0.0
  browser: ^0.10.0
  build_runner: ^0.3.0
  dart_to_js_script_rewriter: ^1.0.0
  test: ^0.12.0
transformers:
  - dart_to_js_script_rewriter
  - polymer:
      entry_points:
        - web/index.html