name: pubby_common
publish_to: none
version: 0.0.0
dependencies:
  angel_model: ^1.0.0
  angel_orm: ^1.0.0-alpha
  angel_serialize: ^1.0.0-alpha
dev_dependencies:
  angel_serialize_generator: ^1.0.0-alpha
  angel_orm_generator: ^1.0.0-alpha
  build_runner: ^0.3.0
  postgres: ^0.9.5